# | 🙑  dismint
# | YW5uaWUgPDM=

format = """
$directory\
$git_branch$git_commit$git_metrics$git_status\
$fill\
$time
$shell [on](fg:#515c74) $os\
$fill\
$bun$python$golang
$character
"""
command_timeout = 500  # ms

[bun]
style = "bold fg:#84ab89"
[python]
style = "bold fg:#84ab89"
[golang]
style = "bold fg:#84ab89"

[shell]
style = "fg:#d3d9b2"
format = "[$indicator]($style)"
disabled = false
[os]
style = "fg:#d3d9b2"
format = "[$name]($style) "
disabled = false

[directory]
style = "fg:#84ab89"
format = "[$path]($style) "
truncate_to_repo = false

[fill]
symbol = " "

[time]
style = "fg:#84ab89"
format = " [$time]($style) "
disabled = false

[character]
success_symbol = "[\\$](fg:#84ab89)"  
error_symbol = "[\\$](fg:#ab8484)"  

[git_branch]
style = "fg:#3e5587"
format = "[on](fg:#515c74) [$branch]($style) "
[git_commit]
style = "fg:#5b606a"
[git_metrics]
added_style = "bold fg:#84ab89"
deleted_style = "bold fg:#ab8484"
disabled = false
[git_status]
style = "bold fg:#a8ab84"
